// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/webmin7761/go-school/homework/final/internal/data/ent/migrate"

	"github.com/webmin7761/go-school/homework/final/internal/data/ent/fare"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Fare is the client for interacting with the Fare builders.
	Fare *FareClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Fare = NewFareClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Fare:   NewFareClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		Fare:   NewFareClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Fare.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Fare.Use(hooks...)
}

// FareClient is a client for the Fare schema.
type FareClient struct {
	config
}

// NewFareClient returns a client for the Fare from the given config.
func NewFareClient(c config) *FareClient {
	return &FareClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `fare.Hooks(f(g(h())))`.
func (c *FareClient) Use(hooks ...Hook) {
	c.hooks.Fare = append(c.hooks.Fare, hooks...)
}

// Create returns a create builder for Fare.
func (c *FareClient) Create() *FareCreate {
	mutation := newFareMutation(c.config, OpCreate)
	return &FareCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Fare entities.
func (c *FareClient) CreateBulk(builders ...*FareCreate) *FareCreateBulk {
	return &FareCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Fare.
func (c *FareClient) Update() *FareUpdate {
	mutation := newFareMutation(c.config, OpUpdate)
	return &FareUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FareClient) UpdateOne(f *Fare) *FareUpdateOne {
	mutation := newFareMutation(c.config, OpUpdateOne, withFare(f))
	return &FareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FareClient) UpdateOneID(id int64) *FareUpdateOne {
	mutation := newFareMutation(c.config, OpUpdateOne, withFareID(id))
	return &FareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Fare.
func (c *FareClient) Delete() *FareDelete {
	mutation := newFareMutation(c.config, OpDelete)
	return &FareDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *FareClient) DeleteOne(f *Fare) *FareDeleteOne {
	return c.DeleteOneID(f.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *FareClient) DeleteOneID(id int64) *FareDeleteOne {
	builder := c.Delete().Where(fare.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FareDeleteOne{builder}
}

// Query returns a query builder for Fare.
func (c *FareClient) Query() *FareQuery {
	return &FareQuery{
		config: c.config,
	}
}

// Get returns a Fare entity by its id.
func (c *FareClient) Get(ctx context.Context, id int64) (*Fare, error) {
	return c.Query().Where(fare.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FareClient) GetX(ctx context.Context, id int64) *Fare {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FareClient) Hooks() []Hook {
	return c.hooks.Fare
}
