// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/webmin7761/go-school/homework/final/internal/data/ent/fare"
	"github.com/webmin7761/go-school/homework/final/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fareFields := schema.Fare{}.Fields()
	_ = fareFields
	// fareDescFirstTravelDate is the schema descriptor for first_travel_date field.
	fareDescFirstTravelDate := fareFields[4].Descriptor()
	// fare.DefaultFirstTravelDate holds the default value on creation for the first_travel_date field.
	fare.DefaultFirstTravelDate = fareDescFirstTravelDate.Default.(func() time.Time)
	// fareDescLastTravelDate is the schema descriptor for last_travel_date field.
	fareDescLastTravelDate := fareFields[5].Descriptor()
	// fare.DefaultLastTravelDate holds the default value on creation for the last_travel_date field.
	fare.DefaultLastTravelDate = fareDescLastTravelDate.Default.(func() time.Time)
	// fareDescCreatedAt is the schema descriptor for created_at field.
	fareDescCreatedAt := fareFields[7].Descriptor()
	// fare.DefaultCreatedAt holds the default value on creation for the created_at field.
	fare.DefaultCreatedAt = fareDescCreatedAt.Default.(func() time.Time)
	// fareDescUpdatedAt is the schema descriptor for updated_at field.
	fareDescUpdatedAt := fareFields[8].Descriptor()
	// fare.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fare.DefaultUpdatedAt = fareDescUpdatedAt.Default.(func() time.Time)
}
