// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.1

package shop

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ShopServiceHTTPServer interface {
	Shopping(context.Context, *ShoppingRequest) (*ShoppingResponse, error)
}

func RegisterShopServiceHTTPServer(s *http.Server, srv ShopServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/shop/shopping", _ShopService_Shopping0_HTTP_Handler(srv))
}

func _ShopService_Shopping0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ShoppingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/shop.ShopService/Shopping")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Shopping(ctx, req.(*ShoppingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShoppingResponse)
		return ctx.Result(200, reply)
	}
}

type ShopServiceHTTPClient interface {
	Shopping(ctx context.Context, req *ShoppingRequest, opts ...http.CallOption) (rsp *ShoppingResponse, err error)
}

type ShopServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewShopServiceHTTPClient(client *http.Client) ShopServiceHTTPClient {
	return &ShopServiceHTTPClientImpl{client}
}

func (c *ShopServiceHTTPClientImpl) Shopping(ctx context.Context, in *ShoppingRequest, opts ...http.CallOption) (*ShoppingResponse, error) {
	var out ShoppingResponse
	pattern := "/v1/shop/shopping"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/shop.ShopService/Shopping"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
