// Code generated by entc, DO NOT EDIT.

package fare

import (
	"time"
)

const (
	// Label holds the string label denoting the fare type in the database.
	Label = "fare"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrgAirport holds the string denoting the org_airport field in the database.
	FieldOrgAirport = "org_airport"
	// FieldArrAirport holds the string denoting the arr_airport field in the database.
	FieldArrAirport = "arr_airport"
	// FieldPassageType holds the string denoting the passage_type field in the database.
	FieldPassageType = "passage_type"
	// FieldFirstTravelDate holds the string denoting the first_travel_date field in the database.
	FieldFirstTravelDate = "first_travel_date"
	// FieldLastTravelDate holds the string denoting the last_travel_date field in the database.
	FieldLastTravelDate = "last_travel_date"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the fare in the database.
	Table = "fares"
)

// Columns holds all SQL columns for fare fields.
var Columns = []string{
	FieldID,
	FieldOrgAirport,
	FieldArrAirport,
	FieldPassageType,
	FieldFirstTravelDate,
	FieldLastTravelDate,
	FieldAmount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFirstTravelDate holds the default value on creation for the "first_travel_date" field.
	DefaultFirstTravelDate func() time.Time
	// DefaultLastTravelDate holds the default value on creation for the "last_travel_date" field.
	DefaultLastTravelDate func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
