// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.1

package travel

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type TravelServiceHTTPServer interface {
	Query(context.Context, *TravelRequest) (*TravelResponse, error)
}

func RegisterTravelServiceHTTPServer(s *http.Server, srv TravelServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/travel/query", _TravelService_Query0_HTTP_Handler(srv))
}

func _TravelService_Query0_HTTP_Handler(srv TravelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TravelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/travel.TravelService/Query")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Query(ctx, req.(*TravelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TravelResponse)
		return ctx.Result(200, reply)
	}
}

type TravelServiceHTTPClient interface {
	Query(ctx context.Context, req *TravelRequest, opts ...http.CallOption) (rsp *TravelResponse, err error)
}

type TravelServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTravelServiceHTTPClient(client *http.Client) TravelServiceHTTPClient {
	return &TravelServiceHTTPClientImpl{client}
}

func (c *TravelServiceHTTPClientImpl) Query(ctx context.Context, in *TravelRequest, opts ...http.CallOption) (*TravelResponse, error) {
	var out TravelResponse
	pattern := "/v1/travel/query"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/travel.TravelService/Query"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
